version: '3.9'

services:
  hotels-api:
    build:
      context: ./hotels-api  # Asegúrate que esta ruta sea correcta
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - MONGO_DB=hotels

  mongo:
    image: mongo:latest
    container_name: my-mongo2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: hotels
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db
